<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2015 Amasty (http://www.amasty.com)
 * @package Amasty_HelloWorld
 */
?>
<div class="amasty-helloworld-block" style="text-align: <?= $this->getTextAlign()?>">
    <!--<img src="data:image/jpeg;base64,'.base64_encode(<?//= $this->getBlockLabel()?> ).'" height="50"/>-->
    <img src="<?= $this->getBlockLabel()?>" height="50"/>
    <?php foreach($this->getCollection() as $item):?>
        <p><label><?= __("Title: ") . $item->getLabel()?></label> -- <label><?=  __("Value: ") . $item->getValue();?></label></p>
    <?php endforeach;?>
</div>