<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2015 Amasty (http://www.amasty.com)
 * @package Amasty_HelloWorld
 */
?>
<div class="amasty-helloworld-block" style="text-align: <?= $this->getTextAlign()?>">
    <img src="http://localhost/magento2/uploadImages/<?= $this->getBlockLabel()?>" style="height:80px;" alt="image label"/>
    <?php foreach($this->getCollection() as $item):?>
        <p><label><?= __("Title: ") . $item->getLabel()?></label> -- <label><?=  __("Value: ") . $item->getValue();?></label></p>
    <?php endforeach;?>
</div>